# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commander', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('year', models.IntegerField(default=0, null=True)),
                ('battle_number', models.IntegerField(default=0)),
                ('attacker_king', models.CharField(max_length=200, null=True, verbose_name=b'Attacker_king')),
                ('attacker_1', models.CharField(max_length=200, null=True, verbose_name=b'Attacker_1')),
                ('attacker_2', models.CharField(max_length=200, null=True, verbose_name=b'Attacker_2')),
                ('attacker_3', models.CharField(max_length=200, null=True, verbose_name=b'Attacker_3')),
                ('attacker_4', models.CharField(max_length=200, null=True, verbose_name=b'Attacker_4')),
                ('defender_king', models.CharField(max_length=200, null=True, verbose_name=b'Defender_king')),
                ('defender_1', models.CharField(max_length=200, null=True, verbose_name=b'Defender_1')),
                ('defender_2', models.CharField(max_length=200, null=True, verbose_name=b'Defender_2')),
                ('defender_3', models.CharField(max_length=200, null=True, verbose_name=b'Defender_3')),
                ('defender_4', models.CharField(max_length=200, null=True, verbose_name=b'Defender_4')),
                ('attacker_coutcome', models.CharField(max_length=200, verbose_name=b'Attacker_outcome')),
                ('battle_type', models.CharField(choices=[(b'ambush', b'Ambush'), (b'siege', b'Siege'), (b'pitched battle', b'Pitched Battle'), (b'razing', b'Razing')], max_length=200, verbose_name=b'Battle_Type')),
                ('major_death', models.IntegerField(default=0)),
                ('major_capture', models.IntegerField(default=0)),
                ('attacker_size', models.PositiveIntegerField(default=0)),
                ('defender_size', models.PositiveIntegerField(default=0)),
                ('summer', models.IntegerField(default=0, null=True)),
                ('location', models.CharField(max_length=100, null=True, verbose_name=b'Location')),
                ('region', models.CharField(max_length=100, null=True, verbose_name=b'Region')),
                ('note', models.CharField(max_length=100, null=True, verbose_name=b'Note')),
                ('attacker_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_attacker_comander', to='commander.AttackerCommander')),
                ('defender_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_defender_commander', to='commander.DefenderCommander')),
            ],
        ),
    ]
