# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gotdetail',
            name='attacker_king',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Attacker_king'),
        ),
        migrations.AlterField(
            model_name='gotdetail',
            name='battle_type',
            field=models.CharField(blank=True, choices=[(b'ambush', b'Ambush'), (b'siege', b'Siege'), (b'pitched battle', b'Pitched Battle'), (b'razing', b'Razing')], max_length=200, verbose_name=b'Battle_Type'),
        ),
        migrations.AlterField(
            model_name='gotdetail',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Location'),
        ),
        migrations.AlterField(
            model_name='gotdetail',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Name'),
        ),
    ]
